### ISSUE TITLE
Locking doesn't work if I share my screen during a meeting in Microsoft Teams or the app is in Full Screen mode

### ISSUE THREAD

**Issue by YuriiKravtsov** [JulyIghor/DockLockPro#3]
App version: DockLock+ 1.0.6
MacOS: Sequoia 15.4 and some previous buidls

Hi 
I have noticed that if I share my screen during a meeting in Microsoft Teams, DockLock does not work and my dock can jump to another screen (monitor) if I move the cursor into the "jump" zone (i.e. normal macOS behavior). 
I also noticed that DockLock does not work if any application is in Full Screen mode.

It seems that a root cause is that in such cases the dock is not visible on the screen.

**Comment by YuriiKravtsov** [comment]
Update
Actually, there are 2 scenarios:
1. When you share your screen using any application (tried with MS Teams and Zoom) - the dock is visible on the screen and is not locked by DockLock+. This is a critical issue because I wouldn't want to show my dock during a presentation on the second screen and sometimes it gets there with an awkward cursor movement.
2. Any application in the Full Screen mode. The dock is not visible in this case but can't be locked by DockLock+ too and if you move your cursor at the bottom of the second screen - the dock will immediately appear there. Not so critical but still annoying.

**Comment by JulyIghor** [comment]
Hi. Thanks. I'll check out what I can do with 1.

As for 2, I can't reproduce it. Also, I have hidden configs to  tweak that.
It would be great if you can run those and pick up the number which does work for you in full-screen mode.
I'll consider that value and make it default in the next update.
To give you config commands, I need to know which app you are using. Is it DockLock Lite or DockLock+?

**Comment by JulyIghor** [comment]
2. Also please confirm that that screen where you are using it in full screen is not enabled in the menu "Allow Dock to Jump to"

**Comment by JulyIghor** [comment]
1. I started a Zoom meeting and shared my external screen. The dock is still locked, so I need more information.
Likely, it is the same reason as it is not working in full-screen mode for you.
Please provide:
Your screen resolution and if it is HiDPI mode.
What is your input device? Is it a mouse or trackpad?
The app name, DockLock Lite or DockLock+

**Comment by YuriiKravtsov** [comment]
Hi
I am using DockLock+
the screen resolution is 1512x982 for the main screen and HiDPI mode is on (it's the default resolution and mode for MacBook Pro 14)
The input device is the mouse, but the problem exists for the trackpad as well
the second monitor is 4k one with 2560x1440 with HiDPI and stacked vertically above the main screen and IS NOT enabled in the menu "Allow Dock to Jump to"

**Comment by JulyIghor** [comment]
Thanks, so let’s try this. Quit the app, run that command in Terminal, don't type it, copy and paste:

`defaults write pro.docklock.plus 'dock·jumpDelay' -int 50`

Start the app and if no changes in fullscreen, lower the number to 40, 30, 20.
Tell me if that fixes the problem. I need to know the highest number of the last parameter up to 100 that still works well.

If it doesn't change anything, reset it to default this way and I'll give you other parameters to change:
`defaults delete pro.docklock.plus 'dock·jumpDelay'`

**Comment by YuriiKravtsov** [comment]
Hi
I've tried all numbers from 50 to 10 and it didn't help in the Full Screen mode
I mean that I quited the app, changed the parameter via Terminal (copied and pasted it), started the app and turn Safari in the FS mode and the Dock jumped to the second monitor when I put the cursor in the bottom area on it
I then repeated this for 40, etc.

**Comment by JulyIghor** [comment]
Sadly, I found a mistake in my code for the second testing parameter. I'll release a fix now so we can try that once Apple approves it.

**Comment by YuriiKravtsov** [comment]
Sounds good, thank you

**Comment by JulyIghor** [comment]
Please run this and confirm it is fixed in full screen mode

`defaults write pro.docklock.plus 'dock·jumpNormalDistance' -float 2.05`

**Comment by YuriiKravtsov** [comment]
I've updated to the version 1.0.7, closed the app, run it in Terminal and reopened the app but still no luck

**Comment by JulyIghor** [comment]
I have not yet released an update. I just noticed another possible reason of that and you confirmed the result. I'll get back to you when update is ready

**Comment by JulyIghor** [comment]
v1.0.8 is now released, please update and confirm is it fixed. If not, I'll provide you test commands.

**Comment by YuriiKravtsov** [comment]
Hi
Sorry, the problem still exists

**Comment by JulyIghor** [comment]
OK, let’s test those, copy and paste two commands, restart the app:

`defaults write pro.docklock.plus 'dock·jumpNormalDistance' -float 5.05`
`defaults write pro.docklock.plus 'dock·jumpHiddenDistance' -float 5.05`

Tell me if it makes any difference in full screen mode, if it fixes the problem, I need the minimum value of the last number that still works.

To revert those options:
`defaults delete pro.docklock.plus 'dock·jumpNormalDistance'`
`defaults delete pro.docklock.plus 'dock·jumpHiddenDistance'`

**Comment by YuriiKravtsov** [comment]
ok, I've tried with these commands - nothing's changed
What is a step and should I increase or decrease the value?

**Comment by JulyIghor** [comment]
Can you please record the screen via Quick Time and show where it is visible: the mouse hitting the bottom and the dock appearing? I need a small part of it. That would help me to understand what to try next.

**Comment by JulyIghor** [comment]
you may try values like 10 or 20, but I think if it not works with 5, I need to see it first

**Comment by YuriiKravtsov** [comment]
https://github.com/user-attachments/assets/fe020b1b-3eb4-4e13-a2c5-2e281a3ec84d
Ok, this is the second monitor which is above my the main one 
DockLock+ was running and Safari was in the FS mode on the main screen - so I moved the cursor from the main screen into the left bottom part of the second one and you can see what happened

**Comment by YuriiKravtsov** [comment]
The funny thing is that even I don't have any app in the Full Screen mode, I still cannot lock the Dock when I am recording the screen - I've just tried to record how it works properly and it does without recording but as soon as I start it, the Dock is moved to the second monitor again (

**Comment by JulyIghor** [comment]
Thanks, try this:

`defaults write pro.docklock.plus 'dock·jumpDelay' -int 1`

**Comment by YuriiKravtsov** [comment]
nope, the same (

**Comment by YuriiKravtsov** [comment]
sorry, I have to go, let's pause the debugging for a while (5-6 hours or more)

**Comment by YuriiKravtsov** [comment]
![Image](https://github.com/user-attachments/assets/4f065c9b-adaa-470d-8617-702e4ddbed54)
if it helps
BTW, I tried to rearrange them in the default order - horizontal one and the issue existed too

**Comment by JulyIghor** [comment]
Thanks, so the dock won't stay locked on the top display or the bottom one?

**Comment by YuriiKravtsov** [comment]
The dock always jumped from the bottom display to the top one - and vice verse if I move the cursor back, at the bottom area of any screen

**Comment by JulyIghor** [comment]
> The dock always jumped from the bottom display to the top one - and vice verse if I move the cursor back, at the bottom area of any screen

Thanks, I still can't reproduce it. I tried to set the exact screen arrangement. Did it happen that you ever changed the dock timeouts via the defaults command in an attempt to keep it locked?

**Comment by JulyIghor** [comment]
I'm asking because on your video it is visible that the Dock appears instantly once your mouse hits the bottom, as for me I can see always a small delay. For example I can hit the bottom of the screen and move the mouse out instantly, the dock won't appear. Is it also possible for you? It would confirm no delay is there. Talk to you later when you have time. I will be happy to fix it with your help.

**Comment by YuriiKravtsov** [comment]
It looks like you were right and the root cause was in the com.apple.dock autohide-delay parameter which was 0 in my settings.

Honestly, I don't remember when and why I adjusted it, but after I set it back to 0.5, which is the default value, and executed 'killall Dock', DockLock+ v 1.0.8 started working properly in FS mode and during sharing or screen recording with all the default settings (I deleted them all before launching the app).

It means that the issue can be closed and I will monitor the app and let you know if anything is changed.

Thank you for a very useful app!

**Comment by JulyIghor** [comment]
Thanks for confirming that. It would be great if you could leave the app review in the Mac App Store. That would be very helpful considering the app is just one month old and has a few ratings only. Thanks for your feedback and for helping to make the app better.
